### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/gehlenborglab-website#12]
Are these something that should have come in automatically, or do we need to supply custom?
```
/img/plus-alt.svg
/favicon.ico
/img/angle-arrow-down.svg
/img/angle-arrow-down-hover.svg
```

**Comment by ngehlenborg** [comment]
Not sure why there are not where they are supposed to be, but I believe they can be found here: https://github.com/18F/jekyll-uswds/tree/master/assets/uswds/img
