### ISSUE TITLE
Port gehlenborg publications

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/gehlenborglab-website#16]
filename convention: smith-2000-journal-of-synthetic-foo.md

**Comment by mccalluc** [comment]
Copy and pasted the html from the old site and ran it through `perl -pne 's/<\/?p[^>]*>//g; s/\s+onclick="[^"]+"//g; s/&nbsp;/ /g; s/(.*"(https?:\/\/[^"]+)".*)/$2\t$1/; s/<\/?a[^>]*>//g; s/\*/\\*/g; s/<\/?em>/*/g; s/<\/?strong>/**/g;'` to produce this markdown. (Something isn't right in the last bit, and I'll fix that, but do you want the whole list?)

@ngehlenborg: Should I go head and make files in `_publications` for all of these? Not hard, but I want to make sure there are no big changes you want to the structure before I jump into this.

(Should Lex and other on-going collaborators also be bold in these citations on the new site?)

> http://www.cancerresearchuk.org/about-us/cancer-news/news-report/2014-10-23-large-study-sheds-light-on-the-genetic-causes-of-thyroid-cancer	The Cancer Genome Atlas Network, incl. **N Gehlenborg**, “Integrated Genomic Characterization of Papillary Thyroid Carcinoma”. *Cell* **159**:676–690 (2014). ***Featured in Clinical Sequencing News, Deutsches Ärtzeblatt, Cancer Research UK News***.
http://www.pnas.org/content/early/2014/10/10/1416074111.abstract	M Parfenov\*, CS Pedamallu\*, **N Gehlenborg**, SS Freeman, L Danilova, CA Bristow, S Lee, A Hadjipanayis, E Ivanova, MD Wilkerson, A Protopopov, L Yang, S Seth, X Song, J Tang, X Ren, J Zhang, A Pantazi, N Santoso, AW Xu, H Mahadeshwar, DA Wheeler, RI Haddad, J Jung, AI Ojesina, N Isaeva, WG Yarbrough, DN Hayes, JR Grandis, AK El-Naggar, M Meyerson, PJ Park, L Chin, JG Seidman, PS Hammerman\*\*, R Kucherlapati\*\*, TCGA Network, “Characterization of HPV and Host-Genome Interactions in Primary Head and Neck Cancers”, *Proceedings of the National Academy of Sciences USA* 2014. Published online ahead of print.
A Lex, **N Gehlenborg**, H Strobelt, R Vuillemot and H Pfister, “UpSet: Visualization of Intersecting Sets”. To appear in *IEEE Transactions on Visualization and Computer Graphics (Proceedings of InfoVis ’14)*.
S Gratzl, **N Gehlenborg**, A Lex, H Pfister and M Streit, “Domino: Extracting, Comparing, and Manipulating Subsets across Multiple Tabular Datasets”. To appear in *IEEE Transactions on Visualization and Computer Graphics (Proceedings of InfoVis ’14)*.
http://www.jku.at/content/e220992/e13428/e13415/e13414?apath=e32681/e225072/e254350/e254686	M Streit\*, A Lex\*, S Gratzl, C Partl, D Schmalstieg, H Pfister, PJ Park\*\* and **N Gehlenborg**\*\*, “Guided Visual Exploration of Genomic Stratifications in Cancer“. *Nature Methods* **11**:884–885 (2014). ***Featured in GenomeWeb, Harvard Medical School News, The Crimson, Harvard SEAS News, JKU Campus News***.
http://www.nature.com/nature/journal/v512/n7515/full/nature13415.html	JWK Ho, YL Jung, Tao Liu, BH Alver, S Lee, K Ikegami, K-A Sohn, A Minoda, MY Tolstorukov, A Appert, SCJ Parker, T Gu, A Kundaje, NC Riddle, E Bishop, TA Egelhofer, SS Hu, AA Alekseyenko, A Rechtsteiner, D Asker, JA Belsky, SK Bowman, QB Chen, RAJ Chen, DS Day, Y Dong, AC Dose, X Duan, CB Epstein, S Ercan, EA Feingold, F Ferrari, J M Garrigues, **N Gehlenborg**, PJ Good, P Haseley, D He, M Herrmann, MM Hoffman, TE Jeffers, PV Kharchenko, PK Zwierz, CV Kotwaliwale, N Kumar, SA Langley, EN Larschan, I Latorre, MW Libbrecht, X Lin, R Park, MJ Pazin, HN Pham, A Plachetka, B Qin, YB Schwartz, N Shoresh, P Stempor, A Vielle, C Wang, CM Whittle, H Xue, RE Kingston, JH Kim, BE Bernstein,AF Dernburg, V Pirrotta, MI Kuroda, WS Noble, TD Tullius, M Kellis, DM MacAlpine, S Strome, SCR Elgin, XS Liu, JD Lieb, J Ahringer, GH Karpen and PJ Park, “Comparative analysis of metazoan chromatin organization“. *Nature* **512**:449–452 (2014).<br>
http://www.the-scientist.com/?articles.view/articleNo/40891/title/Expanding-ENCODE/	***Featured in New York Times, The Scientist***.
http://www.cell.com/cell/abstract/S0092-8674(14)00876-9#	KA Hoadley\*, C Yau\*, DM Wolf\*, AD Cherniack\*, D Tamborero, S Ng, MDM Leiserson, B Niu, MD McLellan, V Uzunangelov, J Zhang, C Kandoth, R Akbani, H Shen, L Omberg, A Chu, AA Margolin, LJ van’t Veer, N Lopez-Bigas, PW Laird, BJ Raphael, L Ding, AG Robertson, LA Byers, GB Mills, JN Weinstein, C Van Waes, Z Chen, EA Collisson, The Cancer Genome Atlas Network incl. **N Gehlenborg**, CC Benz, CM Perou, JM Stuart, “Multi-platform integration of 12 cancer types reveals cell-of-origin classes with distinct molecular signatures”, *Cell* **158**:929–944 (2014).
http://www.nature.com/nature/journal/vaop/ncurrent/full/nature13480.html	The Cancer Genome Atlas Network, incl. <b>N Gehlenborg</b>, “Comprehensive Molecular Characterization of Gastric Adenocarcinoma”, <i>Nature</i>. Published online ahead of print.
http://www.nature.com/nature/journal/vaop/ncurrent/full/nature13385.html	The Cancer Genome Atlas Network, incl. **N Gehlenborg**, “Comprehensive molecular profiling of lung adenocarcinoma“, *Nature*. Published online ahead of print.
http://www.computer.org/csdl/mags/co/2014/05/mco2014050004-abs.html	S Carpendale, M Chen, D Evanko, **N Gehlenborg**, C Görg, L Hunter, F Rowland, M-A Storey, H Strobelt, “Ontologies in Biological Data Visualization“, *IEEE Computer Graphics and Applications ***34**(2):8-15 (2014). ***Featured in IEEE Computer in May 2014.***
http://www.nature.com/nature/journal/vaop/ncurrent/full/nature12965.html	The Cancer Genome Atlas Network, incl. **N Gehlenborg**, “Comprehensive Molecular Characterization of Urothelial Bladder Carcinoma“, *Nature ***507**:315–322 (2014).
http://derstandard.at/1389859388328/Heimische-Forscher-machen-die-Dynamik-hinter-Rankings-sichtbar	S Gratzl, A Lex, **N Gehlenborg**, HP Pfister and M Streit, “LineUp: Visual Analysis of Multi-Attribute Rankings“, *IEEE Transactions on Visualization and Computer Graphics *<b>19</b>:2277-2286 (2013). ***IEEE InfoVis 2013 Best Paper Award | Featured in IEEE Computing Now, Harvard SEAS News, Forbes, Scientific Computing, Der Standard<br>
***
http://www.cell.com/abstract/S0092-8674(13)01208-7	CW Brennan, RG Verhaak, A McKenna, B Campos, H Noushmehr, SR Salama, S Zheng, D Chakravarty, JZ Sanborn, SH Berman, R Beroukhim, B Bernard, CJ Wu, G Genovese, I Shmulevich, J Barnholtz-Sloan, L Zou, R Vegesna, SA Shukla, G Ciriello, WK Yung, W Zhang, C Sougnez, T Mikkelsen, K Aldape, DD Bigner, EG Van Meir, M Prados, A Sloan, KL Black, J Eschbacher, G Finocchiaro, W Friedman, DW Andrews, A Guha, M Iacocca, BP O’Neill, G Foltz, J Myers, DJ Weisenberger, R Penny, R Kucherlapati, CM Perou, DN Hayes, R Gibbs, M Marra, GB Mills, E Lander, P Spellman, R Wilson, C Sander, J Weinstein, M Meyerson, S Gabriel, PW Laird, D Haussler, G Getz, L Chin, The Cancer Genome Atlas Network, incl. **N Gehlenborg**, “The somatic genomic landscape of glioblastoma“, *Cell* **155**:462-77 (2013).
http://www.nature.com/ng/journal/v45/n10/full/ng.2764.html	The Cancer Genome Atlas Network, incl. **N Gehlenborg**, “The Cancer Genome Atlas Pan-Cancer analysis project“, *Nature Genetics* **45**:1113–1120 (2013).
http://www.nature.com/nature/journal/vaop/ncurrent/full/nature12222.html	The Cancer Genome Atlas Network, incl. **N Gehlenborg**, “Comprehensive molecular characterization of clear cell renal cell carcinoma“, *Nature* **499**:43–49 (2013).
http://www.cell.com/abstract/S0092-8674(13)00451-0	L Yang, LJ Luquette, **N Gehlenborg**, R Xi, PS Haseley, C-H Hsieh, C Zhang, X Ren, A Protopopov, L Chin, R Kucherlapati, C Lee, PJ Park and The Cancer Genome Atlas Network, “Diverse mechanisms of somatic structural variations in human cancer genomes“, *Cell ***153**:919-929 (2013).
http://www.genomeweb.com/informatics/februarys-bioinformatics-papers-note	**N Gehlenborg**, MS Noble, G Getz, L Chin and PJ Park, “Nozzle: a report generation toolkit for data analysis pipelines“, *Bioinformatics **29***:1089-1091 (2013). ***Featured in GenomeWeb Bioinformatics Papers of Note for February 2013.***
http://www.nature.com/nature/journal/vaop/ncurrent/full/nature11412.html	The Cancer Genome Atlas Network, incl. **N Gehlenborg**, “Comprehensive molecular portraits of human breast tumours“, *Nature ***490**:61–70 (2012).
http://www.nature.com/nature/journal/vaop/ncurrent/full/nature11404.html	The Cancer Genome Atlas Network, incl. **N Gehlenborg**, “Comprehensive genomic characterization of squamous cell lung cancers“, *Nature* **489**:519–525 (2012).
http://dx.doi.org/10.1038/nature11252	The Cancer Genome Atlas Network, incl. **N Gehlenborg**, “Comprehensive molecular characterization of human colon and rectal cancer“, *Nature* **487**:330–337 (2012) .
http://www.cg.tuwien.ac.at/eurovis2012/awards/best-paper-award/	A Lex, M Streit, H-J Schulz, C Partl, D Schmalstieg, PJ Park, **N Gehlenborg**, “StratomeX: Visual Analysis of Large-Scale Heterogeneous Genomics Data for Cancer Subtype Characterization“, *Computer Graphics Forum* **31**:1175-1184 (2012). Proceedings of EuroVis Conference 2012 - ***3rd Best Paper Award.<br>
***
http://bioinformatics.oxfordjournals.org/content/early/2011/11/20/bioinformatics.btr634.abstract	J Caldas\*, **N Gehlenborg\***, E Kettunen, A Faisal, M Rönty, AG Nicholson, S Knuutila, A Brazma and S Kaski, “ Data-Driven Information Retrieval in Heterogeneous Collections of Transcriptomics Data Links SIM2s to Malignant Pleural Mesothelioma“, *Bioinformatics* **28**(2):246-253 (2012).
http://www.nature.com/nmeth/journal/v7/n3s/abs/nmeth.1436.html	**N Gehlenborg**, SI O’Donoghue, NS Baliga, A Goesmann, MA Hibbs, H Kitano, O Kohlbacher, H Neuweger, R Schneider, D Tenenbaum and AC Gavin, “Visualization of Omics Data for Systems Biology“, *Nature Methods* **7**(3):S56-S68 (2010).
http://dx.doi.org/10.1109/ICASSP.2010.5495665	J Peltonen, H Aidos, **N Gehlenborg**, A Brazma and S Kaski, “An Information Retrieval Perspective on Visualization of Gene Expression Data with Ontological Annotation“. In Proceedings of the *IEEE 2010 International Conference on Acoustics, Speech, and Signal Processing (ICASSP 2010)*, 2178-2181 (2010).
http://dx.doi.org/10.1093/database/bap011	**N Gehlenborg\***, D Hwang\*, IY Lee\*, H Yoo, B Petritis, D Baxter, R Pitstick, B Marzolf, SJ DeArmond, GA Carlson and LE Hood, “The Prion Disease Database: A Comprehensive Transcriptome Resource for Systems Biology Research in Prion Diseases“, *Database* 2009:bap011 (2009).
http://dx.doi.org/10.1093/bioinformatics/btp215 	J Caldas, **N Gehlenborg**, A Faisal, A Brazma and S Kaski, “Probabilistic retrieval and visualization of biologically relevant microarray experiments“, *Bioinformatics* **25**(12):i145-i153 (2009).
http://dx.doi.org/10.1038/msb.2009.10	D Hwang\*, IY Lee\*, H Yoo\*, **N Gehlenborg**, J Cho, B Petritis, D Baxter, R Pitstick, R Young, D Spicer, N Price, JG Hohmann, SJ DeArmond, GA Carlson and LE Hood, “A Systems Approach to Prion Disease“, *Molecular Systems Biology ***5**:252 (2009).
http://dx.doi.org/10.1093/bioinformatics/btp005	**N Gehlenborg**, W Yan, I Lee, H Yoo, K Nieselt, D Hwang, R Aebersold, L Hood, “Prequips – An Extensible Software Platform for Integration, Visualization and Analysis of LC-MS/MS Proteomics Data“, *Bioinformatics* **25**(5):682-683 (2009).
http://dx.doi.org/10.1074/mcp.M700498-MCP200	A Schmidt, **N Gehlenborg**, B Bodenmiller, LN Mueller, D Campbell, M Mueller, R Aebersold and B Domon, “An integrated, directed mass spectrometric approach for in-depth characterization of complex peptide mixtures“, *Molecular &amp; Cellular Proteomics* **7**:2138-2150 (2008).
http://dx.doi.org/10.1093/bioinformatics/btl070	J Dietzsch\*, **N Gehlenborg**\* and K Nieselt, “Mayday – A Microarray Data Analysis Workbench“, *Bioinformatics* **22**(8):1010-1012 (2006).
http://dx.doi.org/10.1057/palgrave.ivs.9500094	**N Gehlenborg**, J Dietzsch and K Nieselt, “A Framework for Visualization of Microarray Data and Integrated Meta Information“, *Information Visualization* **4**(3):164-175 (2005).
<h2>Commentaries, Editorials, Book Chapters &amp; Published Abstracts</h2>
http://www.nature.com/nmeth/journal/v11/n8/abs/nmeth.3033.html	A Lex and** N Gehlenborg**, “Points of View: Sets and Intersections“, *Nature Methods* **11**(8):779 (2014).
http://www.nature.com/nmeth/journal/v11/n2/abs/nmeth.2807.html	M Streit and** N Gehlenborg**, “Points of View: Bar Charts and Box Plots“, *Nature Methods* **11**(2):117 (2014).
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3814497/	S Ho Sui, E Merrill, **N Gehlenborg**, P Haseley, I Sytchev, R Park, P Rocca-Serra, S Corlosquet, A Gonzalez-Beltran, E Maguire, O Hofmann, PJ Park, S Das, SA Sansone, W Hide, “The Stem Cell Commons: an exemplar for data integration in the biomedical domain driven by the ISA framework“, *AMIA Summits Translational Science Proceedings* **2013**:70 (2013).
http://www.ploscompbiol.org/article/metrics/info%3Adoi%2F10.1371%2Fjournal.pcbi.1002834	J de Ridder\*, T Abeel\*, M Michaut, VP Satagopam and **N Gehlenborg**, “Don’t Wear Your New Shoes (Yet): Taking the Right Steps to Become a Successful Principal Investigator” (Workshop Report), *PLoS Computational Biology* **9**(1):e1002834 (2013). ***Most viewed article in PLoS Computational Biology during February/March 2013 with more than 12,000 views in 30 days.***
http://www.nature.com/nmeth/journal/v9/n10/full/nmeth.2186.html	**N Gehlenborg** and B Wong, “Points of View: Power of the Plane“, *Nature Methods* **9**(10):935 (2012).
http://www.nature.com/nmeth/journal/v9/n9/full/nmeth.2151.html	**N Gehlenborg** and B Wong, “Points of View: Into the Third Dimension“, *Nature Methods* **9**(9):851 (2012).
http://www.nature.com/nmeth/journal/v9/n8/full/nmeth.2134.html	**N Gehlenborg** and B Wong, “Points of View: Mapping Quantitative Data to Color“, *Nature Methods* **9**(8):769 (2012).
http://www.nature.com/nmeth/journal/v9/n4/abs/nmeth.1944.html	**N Gehlenborg** and B Wong, “Points of View: Integrating Data“, *Nature Methods* **9**(4):315 (2012).
http://www.nature.com/nmeth/journal/v9/n3/abs/nmeth.1902.html	**N Gehlenborg** and B Wong, “Points of View: Heat maps“, *Nature Methods* **9**(3):213 (2012).
http://www.nature.com/nmeth/journal/v9/n2/abs/nmeth.1862.html	**N Gehlenborg** and B Wong, “Points of View: Networks“, *Nature Methods* **9**(2):115 (2012).
http://www.nature.com/nmeth/journal/v7/n3s/abs/nmeth.f.301.html	SI O’Donoghue, AC Gavin, **N Gehlenborg**, DS Goodsell, JK Heriche, CB Nielsen, C North, AJ Olson, JB Procter, DW Shattuck, T Walter and B Wong, “Visualizing biological data – now and in the future“. *Nature Methods* **7**(3):S2-S4 (2010).
http://www.biomedcentral.com/1471-2105/10/S13/O7	**N Gehlenborg** and A Brazma, “Visualization of Large Microarray Experiments with Space Maps” (Abstract), *BMC Bioinformatics* **10**(Suppl 13):O7 (2009).
http://www.biomedcentral.com/1471-2105/10/S13/P1	J Caldas, **N Gehlenborg**, A Faisal, A Brazma and S Kaski, “Probabilistic Retrieval and Visualization of Biologically Relevant Microarray Experiments” (Abstract), *BMC Bioinformatics* **10**(Suppl 13):P1 (2009).
http://dx.doi.org/10.1186/1471-2105-9-S10-I1	L Peixoto, **N Gehlenborg** and S Chandra Janga (Eds.), “Highlights from the Fourth International Society for Computational Biology (ISCB) Student Council Symposium at the Sixteenth Annual International Conference on Intelligent Systems for Molecular Biology (ISMB)“, *BMC Bioinformatics* **9**(Suppl 10):I1 (2008).
http://dx.doi.org/10.1371/journal.pcbi.1000080	M Corpas, **N Gehlenborg**, S Chandra Janga and PE Bourne, “Ten Simple Rules for Organizing a Scientific Meeting“, *PLoS Computational Biology* **4**(6):e1000080 (2008).
http://dx.doi.org/10.1186/1471-2105-8-S8-I1	**N Gehlenborg**, M Corpas and S Chandra Janga (Eds.), “Highlights from the Third International Society for Computational Biology (ISCB) Student Council Symposium at the Fifteenth Annual International Conference on Intelligent Systems for Molecular Biology (ISMB)“, *BMC Bioinformatics* **8**(Suppl 8):I1 (2007).
http://www.amazon.de/Aktuelle-Trends-Softwareforschung-Tagungsband-Software-Forschungstag/dp/3898644138	**N Gehlenborg**, “Visualisierung für DNA-Chip-Analysen“, in D. Spath, K. Haasis and D. Klumpp (Eds.), Aktuelle Trends in der Softwareforschung (Vol. 3), 259-270, IRB Fraunhofer Verlag, Stuttgart, Germany (2005). In German.
\* equally contributing authors
<h2>Theses</h2>
http://gehlenborg.com/wp-content/uploads/2012/11/nils-gehlenborg_phd.pdf	**N Gehlenborg**, “Visualization and Exploration of Transcriptomics Data“, *PhD Thesis*, University of Cambridge, United Kingdom (2010).
http://gehlenborg.com/wp-content/uploads/2011/12/nils-gehlenborg_masters.pdf	**N Gehlenborg**, “Visualization and Integration of Liquid Chromatography/Mass Spectrometry Proteomics Data“, *Diplomarbeit (eq. Masters Thesis)*, University of Tübingen, Germany (2006).
http://gehlenborg.com/wp-content/uploads/2011/12/nils-gehlenborg_bachelors.pdf	**N Gehlenborg**, “Mayday – Microarray Data Analysis“, *Studienarbeit (eq. Bachelors Thesis)*, University of Tübingen, Germany (2003).

**Comment by ngehlenborg** [comment]
Wow, impressive expression! Why don't you give it a try? We'll most likely have to do some manual curation in any case.
