### ISSUE TITLE
Add LineUp as project? And phys.org article?

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/gehlenborglab-website#186]
Googling "Nils Gehlenborg" found this nice article: [What's behind a No. 1 ranking? Open-source LineUp software enables granular analysis of subjective ranking systems](https://phys.org/news/2014-01-open-source-lineup-software-enables-granular.html).

- Add an entry in media.yml?
- Add _projects/lineup.md?

Assign back to me if you'd like this, or close if you don't.

**Comment by ngehlenborg** [comment]
Looking good. Just add to media for now. Thanks!
