### ISSUE TITLE
confirm links between objects

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/gehlenborglab-website#21]
given news + people + project + publication:  complete graph - news item<->project

**Comment by mccalluc** [comment]
@ngehlenborg : Do you have strong opinions about "project <-> publication": Which side should be the one that records the id?

(If you don't have an opinion, that's great, too: I'd probably put it on publication.)

**Comment by ngehlenborg** [comment]
in the long run bidirectional, for now publications with the projects

**Comment by mccalluc** [comment]
fixed in master. (It is bidirectional: Even for relationships that would be modeled as many-to-many, we only want to record the foreign IDs on one side of the relationship, so we're not wasting time with duplicate data entry.)
