### ISSUE TITLE
add page about requesting letters of recommendation

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/gehlenborglab-website#230]
Content: https://docs.google.com/document/d/1ExvDEp0ogNeCFt1ThCgfRwfcLqC6fymQt-R76oyk7bQ/edit

Please add a new "/education" route and put this into "/education/letters-of-recommendation". For now, this won't be linked from any menus (I will share the direct link with students who need it) and there won't be a separate "Education" entry in the site navigation (but will likely get added soon).

**Comment by mccalluc** [comment]
Fixed by #231
