### ISSUE TITLE
Update lab name

### ISSUE THREAD

**Issue by lchoy** [hms-dbmi/gehlenborglab-website#398]
With the lab's name change to HIDIVE, content on the website should be updated such that everything that says ‘Gehlenborg Lab’ should be ‘HIDIVE Lab’ and to give a bit of explanation about the same.

**Comment by sehilyi** [comment]
Just to confirm – is it HIDIVE with the upper letter "I"s, because I see both cases, H**I**DIVE and H**i**DIVE, used by members :)

cc @ngehlenborg

**Comment by ngehlenborg** [comment]
Let's go for "HIDIVE" on the website for now and decide if we want to go for "HiDIVE" if the logo works better with that.
