### ISSUE TITLE
Fill in content for at least one post (or get rid of this feature)

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/gehlenborglab-website#5]
Right now, http://127.0.0.1:4000/feed.xml just has "hello world" stuff.

Nils: I think you said you didn't like the date style urls, ie: http://localhost:4000/2017/03/08/welcome-to-jekyll.html

Do we even need the blogish functionality? ie, Is it important that some pages be sorted by date? What are the requirements?

**Comment by ngehlenborg** [comment]
Preferred post format: `.../news/YYYY-MM-DD_title-of-the-post.html`

**Comment by mccalluc** [comment]
I think this is done. (Though I'm a little confused about what we decided about the urls.)
