### ISSUE TITLE
Should subsection titles be more prominent?

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/gehlenborglab-website#7]
http://localhost:4000/team/open-positions/

Subsection titles are nearly indistinguishable from body text... Are we using the wrong styles, or should we tweak the styles?

**Comment by ngehlenborg** [comment]
I think the style is fine but I played around with the fonts before handing the site over to you. I will probably go back to a sans serif/serif font combination and then that will look ok again.

Possibly I will even go back to the default fonts (https://standards.usa.gov/).

**Comment by mccalluc** [comment]
Looks fine now.
