### ISSUE TITLE
create collection for media mentions

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/gehlenborglab-website#79]
Like news item.

Examples: http://vdl.sci.utah.edu/team/lex/#press or http://compepi.org/news/.

**Comment by mccalluc** [comment]
Connected to project and person. Has title, date, url, and "outlet". (Or "channel" / "source" / etc. : Our name for this field is just an implementation detail.)

**Comment by mccalluc** [comment]
Machinery is in place. Style might still be tweaked. My sense is that this for going forward, but let me know if I should import some particular list.
